# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kim5/OASISBloc_github/OASISBlocChain

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kim5/OASISBloc_github/OASISBlocChain

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"base\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kim5/OASISBloc_github/OASISBlocChain/CMakeFiles /home/kim5/OASISBloc_github/OASISBlocChain/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kim5/OASISBloc_github/OASISBlocChain/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named base-install

# Build rule for target.
base-install: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 base-install
.PHONY : base-install

# fast build rule for target.
base-install/fast:
	$(MAKE) -f CMakeFiles/base-install.dir/build.make CMakeFiles/base-install.dir/build
.PHONY : base-install/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named fc

# Build rule for target.
fc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fc
.PHONY : fc

# fast build rule for target.
fc/fast:
	$(MAKE) -f libraries/fc/CMakeFiles/fc.dir/build.make libraries/fc/CMakeFiles/fc.dir/build
.PHONY : fc/fast

#=============================================================================
# Target rules for targets named secp256k1

# Build rule for target.
secp256k1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 secp256k1
.PHONY : secp256k1

# fast build rule for target.
secp256k1/fast:
	$(MAKE) -f libraries/fc/secp256k1/CMakeFiles/secp256k1.dir/build.make libraries/fc/secp256k1/CMakeFiles/secp256k1.dir/build
.PHONY : secp256k1/fast

#=============================================================================
# Target rules for targets named test_cypher_suites

# Build rule for target.
test_cypher_suites: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cypher_suites
.PHONY : test_cypher_suites

# fast build rule for target.
test_cypher_suites/fast:
	$(MAKE) -f libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/build.make libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/build
.PHONY : test_cypher_suites/fast

#=============================================================================
# Target rules for targets named builtins

# Build rule for target.
builtins: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 builtins
.PHONY : builtins

# fast build rule for target.
builtins/fast:
	$(MAKE) -f libraries/builtins/CMakeFiles/builtins.dir/build.make libraries/builtins/CMakeFiles/builtins.dir/build
.PHONY : builtins/fast

#=============================================================================
# Target rules for targets named softfloat

# Build rule for target.
softfloat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 softfloat
.PHONY : softfloat

# fast build rule for target.
softfloat/fast:
	$(MAKE) -f libraries/softfloat/CMakeFiles/softfloat.dir/build.make libraries/softfloat/CMakeFiles/softfloat.dir/build
.PHONY : softfloat/fast

#=============================================================================
# Target rules for targets named chainbase

# Build rule for target.
chainbase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chainbase
.PHONY : chainbase

# fast build rule for target.
chainbase/fast:
	$(MAKE) -f libraries/chainbase/CMakeFiles/chainbase.dir/build.make libraries/chainbase/CMakeFiles/chainbase.dir/build
.PHONY : chainbase/fast

#=============================================================================
# Target rules for targets named chainbase_test

# Build rule for target.
chainbase_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chainbase_test
.PHONY : chainbase_test

# fast build rule for target.
chainbase_test/fast:
	$(MAKE) -f libraries/chainbase/test/CMakeFiles/chainbase_test.dir/build.make libraries/chainbase/test/CMakeFiles/chainbase_test.dir/build
.PHONY : chainbase_test/fast

#=============================================================================
# Target rules for targets named Inline

# Build rule for target.
Inline: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Inline
.PHONY : Inline

# fast build rule for target.
Inline/fast:
	$(MAKE) -f libraries/wasm-jit/Include/Inline/CMakeFiles/Inline.dir/build.make libraries/wasm-jit/Include/Inline/CMakeFiles/Inline.dir/build
.PHONY : Inline/fast

#=============================================================================
# Target rules for targets named IR

# Build rule for target.
IR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IR
.PHONY : IR

# fast build rule for target.
IR/fast:
	$(MAKE) -f libraries/wasm-jit/Source/IR/CMakeFiles/IR.dir/build.make libraries/wasm-jit/Source/IR/CMakeFiles/IR.dir/build
.PHONY : IR/fast

#=============================================================================
# Target rules for targets named Logging

# Build rule for target.
Logging: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Logging
.PHONY : Logging

# fast build rule for target.
Logging/fast:
	$(MAKE) -f libraries/wasm-jit/Source/Logging/CMakeFiles/Logging.dir/build.make libraries/wasm-jit/Source/Logging/CMakeFiles/Logging.dir/build
.PHONY : Logging/fast

#=============================================================================
# Target rules for targets named Platform

# Build rule for target.
Platform: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Platform
.PHONY : Platform

# fast build rule for target.
Platform/fast:
	$(MAKE) -f libraries/wasm-jit/Source/Platform/CMakeFiles/Platform.dir/build.make libraries/wasm-jit/Source/Platform/CMakeFiles/Platform.dir/build
.PHONY : Platform/fast

#=============================================================================
# Target rules for targets named Runtime

# Build rule for target.
Runtime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Runtime
.PHONY : Runtime

# fast build rule for target.
Runtime/fast:
	$(MAKE) -f libraries/wasm-jit/Source/Runtime/CMakeFiles/Runtime.dir/build.make libraries/wasm-jit/Source/Runtime/CMakeFiles/Runtime.dir/build
.PHONY : Runtime/fast

#=============================================================================
# Target rules for targets named WASM

# Build rule for target.
WASM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WASM
.PHONY : WASM

# fast build rule for target.
WASM/fast:
	$(MAKE) -f libraries/wasm-jit/Source/WASM/CMakeFiles/WASM.dir/build.make libraries/wasm-jit/Source/WASM/CMakeFiles/WASM.dir/build
.PHONY : WASM/fast

#=============================================================================
# Target rules for targets named WAST

# Build rule for target.
WAST: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WAST
.PHONY : WAST

# fast build rule for target.
WAST/fast:
	$(MAKE) -f libraries/wasm-jit/Source/WAST/CMakeFiles/WAST.dir/build.make libraries/wasm-jit/Source/WAST/CMakeFiles/WAST.dir/build
.PHONY : WAST/fast

#=============================================================================
# Target rules for targets named appbase_version

# Build rule for target.
appbase_version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 appbase_version
.PHONY : appbase_version

# fast build rule for target.
appbase_version/fast:
	$(MAKE) -f libraries/appbase/CMakeFiles/appbase_version.dir/build.make libraries/appbase/CMakeFiles/appbase_version.dir/build
.PHONY : appbase_version/fast

#=============================================================================
# Target rules for targets named appbase

# Build rule for target.
appbase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 appbase
.PHONY : appbase

# fast build rule for target.
appbase/fast:
	$(MAKE) -f libraries/appbase/CMakeFiles/appbase.dir/build.make libraries/appbase/CMakeFiles/appbase.dir/build
.PHONY : appbase/fast

#=============================================================================
# Target rules for targets named appbase_example

# Build rule for target.
appbase_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 appbase_example
.PHONY : appbase_example

# fast build rule for target.
appbase_example/fast:
	$(MAKE) -f libraries/appbase/examples/CMakeFiles/appbase_example.dir/build.make libraries/appbase/examples/CMakeFiles/appbase_example.dir/build
.PHONY : appbase_example/fast

#=============================================================================
# Target rules for targets named eosio_chain

# Build rule for target.
eosio_chain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eosio_chain
.PHONY : eosio_chain

# fast build rule for target.
eosio_chain/fast:
	$(MAKE) -f libraries/chain/CMakeFiles/eosio_chain.dir/build.make libraries/chain/CMakeFiles/eosio_chain.dir/build
.PHONY : eosio_chain/fast

#=============================================================================
# Target rules for targets named eosio_testing

# Build rule for target.
eosio_testing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eosio_testing
.PHONY : eosio_testing

# fast build rule for target.
eosio_testing/fast:
	$(MAKE) -f libraries/testing/CMakeFiles/eosio_testing.dir/build.make libraries/testing/CMakeFiles/eosio_testing.dir/build
.PHONY : eosio_testing/fast

#=============================================================================
# Target rules for targets named run-tests

# Build rule for target.
run-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-tests
.PHONY : run-tests

# fast build rule for target.
run-tests/fast:
	$(MAKE) -f libraries/wabt/CMakeFiles/run-tests.dir/build.make libraries/wabt/CMakeFiles/run-tests.dir/build
.PHONY : run-tests/fast

#=============================================================================
# Target rules for targets named everything

# Build rule for target.
everything: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 everything
.PHONY : everything

# fast build rule for target.
everything/fast:
	$(MAKE) -f libraries/wabt/CMakeFiles/everything.dir/build.make libraries/wabt/CMakeFiles/everything.dir/build
.PHONY : everything/fast

#=============================================================================
# Target rules for targets named wabt

# Build rule for target.
wabt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wabt
.PHONY : wabt

# fast build rule for target.
wabt/fast:
	$(MAKE) -f libraries/wabt/CMakeFiles/wabt.dir/build.make libraries/wabt/CMakeFiles/wabt.dir/build
.PHONY : wabt/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f libraries/yubihsm/CMakeFiles/dist.dir/build.make libraries/yubihsm/CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named cppcheck

# Build rule for target.
cppcheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cppcheck
.PHONY : cppcheck

# fast build rule for target.
cppcheck/fast:
	$(MAKE) -f libraries/yubihsm/CMakeFiles/cppcheck.dir/build.make libraries/yubihsm/CMakeFiles/cppcheck.dir/build
.PHONY : cppcheck/fast

#=============================================================================
# Target rules for targets named yubihsm_usb

# Build rule for target.
yubihsm_usb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yubihsm_usb
.PHONY : yubihsm_usb

# fast build rule for target.
yubihsm_usb/fast:
	$(MAKE) -f libraries/yubihsm/lib/CMakeFiles/yubihsm_usb.dir/build.make libraries/yubihsm/lib/CMakeFiles/yubihsm_usb.dir/build
.PHONY : yubihsm_usb/fast

#=============================================================================
# Target rules for targets named yubihsm

# Build rule for target.
yubihsm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yubihsm
.PHONY : yubihsm

# fast build rule for target.
yubihsm/fast:
	$(MAKE) -f libraries/yubihsm/lib/CMakeFiles/yubihsm.dir/build.make libraries/yubihsm/lib/CMakeFiles/yubihsm.dir/build
.PHONY : yubihsm/fast

#=============================================================================
# Target rules for targets named yubihsm_static

# Build rule for target.
yubihsm_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yubihsm_static
.PHONY : yubihsm_static

# fast build rule for target.
yubihsm_static/fast:
	$(MAKE) -f libraries/yubihsm/lib/CMakeFiles/yubihsm_static.dir/build.make libraries/yubihsm/lib/CMakeFiles/yubihsm_static.dir/build
.PHONY : yubihsm_static/fast

#=============================================================================
# Target rules for targets named yubihsm_http

# Build rule for target.
yubihsm_http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yubihsm_http
.PHONY : yubihsm_http

# fast build rule for target.
yubihsm_http/fast:
	$(MAKE) -f libraries/yubihsm/lib/CMakeFiles/yubihsm_http.dir/build.make libraries/yubihsm/lib/CMakeFiles/yubihsm_http.dir/build
.PHONY : yubihsm_http/fast

#=============================================================================
# Target rules for targets named test_pbkdf2

# Build rule for target.
test_pbkdf2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_pbkdf2
.PHONY : test_pbkdf2

# fast build rule for target.
test_pbkdf2/fast:
	$(MAKE) -f libraries/yubihsm/lib/tests/CMakeFiles/test_pbkdf2.dir/build.make libraries/yubihsm/lib/tests/CMakeFiles/test_pbkdf2.dir/build
.PHONY : test_pbkdf2/fast

#=============================================================================
# Target rules for targets named test_parsing

# Build rule for target.
test_parsing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_parsing
.PHONY : test_parsing

# fast build rule for target.
test_parsing/fast:
	$(MAKE) -f libraries/yubihsm/lib/tests/CMakeFiles/test_parsing.dir/build.make libraries/yubihsm/lib/tests/CMakeFiles/test_parsing.dir/build
.PHONY : test_parsing/fast

#=============================================================================
# Target rules for targets named test_usb_url

# Build rule for target.
test_usb_url: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_usb_url
.PHONY : test_usb_url

# fast build rule for target.
test_usb_url/fast:
	$(MAKE) -f libraries/yubihsm/lib/tests/CMakeFiles/test_usb_url.dir/build.make libraries/yubihsm/lib/tests/CMakeFiles/test_usb_url.dir/build
.PHONY : test_usb_url/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) -f libraries/yubihsm/lib/tests/CMakeFiles/test_util.dir/build.make libraries/yubihsm/lib/tests/CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

#=============================================================================
# Target rules for targets named net_plugin

# Build rule for target.
net_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net_plugin
.PHONY : net_plugin

# fast build rule for target.
net_plugin/fast:
	$(MAKE) -f plugins/net_plugin/CMakeFiles/net_plugin.dir/build.make plugins/net_plugin/CMakeFiles/net_plugin.dir/build
.PHONY : net_plugin/fast

#=============================================================================
# Target rules for targets named net_api_plugin

# Build rule for target.
net_api_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net_api_plugin
.PHONY : net_api_plugin

# fast build rule for target.
net_api_plugin/fast:
	$(MAKE) -f plugins/net_api_plugin/CMakeFiles/net_api_plugin.dir/build.make plugins/net_api_plugin/CMakeFiles/net_api_plugin.dir/build
.PHONY : net_api_plugin/fast

#=============================================================================
# Target rules for targets named http_plugin

# Build rule for target.
http_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_plugin
.PHONY : http_plugin

# fast build rule for target.
http_plugin/fast:
	$(MAKE) -f plugins/http_plugin/CMakeFiles/http_plugin.dir/build.make plugins/http_plugin/CMakeFiles/http_plugin.dir/build
.PHONY : http_plugin/fast

#=============================================================================
# Target rules for targets named http_client_plugin

# Build rule for target.
http_client_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_client_plugin
.PHONY : http_client_plugin

# fast build rule for target.
http_client_plugin/fast:
	$(MAKE) -f plugins/http_client_plugin/CMakeFiles/http_client_plugin.dir/build.make plugins/http_client_plugin/CMakeFiles/http_client_plugin.dir/build
.PHONY : http_client_plugin/fast

#=============================================================================
# Target rules for targets named chain_plugin

# Build rule for target.
chain_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chain_plugin
.PHONY : chain_plugin

# fast build rule for target.
chain_plugin/fast:
	$(MAKE) -f plugins/chain_plugin/CMakeFiles/chain_plugin.dir/build.make plugins/chain_plugin/CMakeFiles/chain_plugin.dir/build
.PHONY : chain_plugin/fast

#=============================================================================
# Target rules for targets named chain_api_plugin

# Build rule for target.
chain_api_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chain_api_plugin
.PHONY : chain_api_plugin

# fast build rule for target.
chain_api_plugin/fast:
	$(MAKE) -f plugins/chain_api_plugin/CMakeFiles/chain_api_plugin.dir/build.make plugins/chain_api_plugin/CMakeFiles/chain_api_plugin.dir/build
.PHONY : chain_api_plugin/fast

#=============================================================================
# Target rules for targets named producer_plugin

# Build rule for target.
producer_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 producer_plugin
.PHONY : producer_plugin

# fast build rule for target.
producer_plugin/fast:
	$(MAKE) -f plugins/producer_plugin/CMakeFiles/producer_plugin.dir/build.make plugins/producer_plugin/CMakeFiles/producer_plugin.dir/build
.PHONY : producer_plugin/fast

#=============================================================================
# Target rules for targets named producer_api_plugin

# Build rule for target.
producer_api_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 producer_api_plugin
.PHONY : producer_api_plugin

# fast build rule for target.
producer_api_plugin/fast:
	$(MAKE) -f plugins/producer_api_plugin/CMakeFiles/producer_api_plugin.dir/build.make plugins/producer_api_plugin/CMakeFiles/producer_api_plugin.dir/build
.PHONY : producer_api_plugin/fast

#=============================================================================
# Target rules for targets named history_plugin

# Build rule for target.
history_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 history_plugin
.PHONY : history_plugin

# fast build rule for target.
history_plugin/fast:
	$(MAKE) -f plugins/history_plugin/CMakeFiles/history_plugin.dir/build.make plugins/history_plugin/CMakeFiles/history_plugin.dir/build
.PHONY : history_plugin/fast

#=============================================================================
# Target rules for targets named history_api_plugin

# Build rule for target.
history_api_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 history_api_plugin
.PHONY : history_api_plugin

# fast build rule for target.
history_api_plugin/fast:
	$(MAKE) -f plugins/history_api_plugin/CMakeFiles/history_api_plugin.dir/build.make plugins/history_api_plugin/CMakeFiles/history_api_plugin.dir/build
.PHONY : history_api_plugin/fast

#=============================================================================
# Target rules for targets named state_history_plugin

# Build rule for target.
state_history_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 state_history_plugin
.PHONY : state_history_plugin

# fast build rule for target.
state_history_plugin/fast:
	$(MAKE) -f plugins/state_history_plugin/CMakeFiles/state_history_plugin.dir/build.make plugins/state_history_plugin/CMakeFiles/state_history_plugin.dir/build
.PHONY : state_history_plugin/fast

#=============================================================================
# Target rules for targets named wallet_plugin

# Build rule for target.
wallet_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wallet_plugin
.PHONY : wallet_plugin

# fast build rule for target.
wallet_plugin/fast:
	$(MAKE) -f plugins/wallet_plugin/CMakeFiles/wallet_plugin.dir/build.make plugins/wallet_plugin/CMakeFiles/wallet_plugin.dir/build
.PHONY : wallet_plugin/fast

#=============================================================================
# Target rules for targets named wallet_api_plugin

# Build rule for target.
wallet_api_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wallet_api_plugin
.PHONY : wallet_api_plugin

# fast build rule for target.
wallet_api_plugin/fast:
	$(MAKE) -f plugins/wallet_api_plugin/CMakeFiles/wallet_api_plugin.dir/build.make plugins/wallet_api_plugin/CMakeFiles/wallet_api_plugin.dir/build
.PHONY : wallet_api_plugin/fast

#=============================================================================
# Target rules for targets named txn_test_gen_plugin

# Build rule for target.
txn_test_gen_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 txn_test_gen_plugin
.PHONY : txn_test_gen_plugin

# fast build rule for target.
txn_test_gen_plugin/fast:
	$(MAKE) -f plugins/txn_test_gen_plugin/CMakeFiles/txn_test_gen_plugin.dir/build.make plugins/txn_test_gen_plugin/CMakeFiles/txn_test_gen_plugin.dir/build
.PHONY : txn_test_gen_plugin/fast

#=============================================================================
# Target rules for targets named db_size_api_plugin

# Build rule for target.
db_size_api_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db_size_api_plugin
.PHONY : db_size_api_plugin

# fast build rule for target.
db_size_api_plugin/fast:
	$(MAKE) -f plugins/db_size_api_plugin/CMakeFiles/db_size_api_plugin.dir/build.make plugins/db_size_api_plugin/CMakeFiles/db_size_api_plugin.dir/build
.PHONY : db_size_api_plugin/fast

#=============================================================================
# Target rules for targets named login_plugin

# Build rule for target.
login_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 login_plugin
.PHONY : login_plugin

# fast build rule for target.
login_plugin/fast:
	$(MAKE) -f plugins/login_plugin/CMakeFiles/login_plugin.dir/build.make plugins/login_plugin/CMakeFiles/login_plugin.dir/build
.PHONY : login_plugin/fast

#=============================================================================
# Target rules for targets named test_control_plugin

# Build rule for target.
test_control_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_control_plugin
.PHONY : test_control_plugin

# fast build rule for target.
test_control_plugin/fast:
	$(MAKE) -f plugins/test_control_plugin/CMakeFiles/test_control_plugin.dir/build.make plugins/test_control_plugin/CMakeFiles/test_control_plugin.dir/build
.PHONY : test_control_plugin/fast

#=============================================================================
# Target rules for targets named test_control_api_plugin

# Build rule for target.
test_control_api_plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_control_api_plugin
.PHONY : test_control_api_plugin

# fast build rule for target.
test_control_api_plugin/fast:
	$(MAKE) -f plugins/test_control_api_plugin/CMakeFiles/test_control_api_plugin.dir/build.make plugins/test_control_api_plugin/CMakeFiles/test_control_api_plugin.dir/build
.PHONY : test_control_api_plugin/fast

#=============================================================================
# Target rules for targets named nodeos

# Build rule for target.
nodeos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nodeos
.PHONY : nodeos

# fast build rule for target.
nodeos/fast:
	$(MAKE) -f programs/nodeos/CMakeFiles/nodeos.dir/build.make programs/nodeos/CMakeFiles/nodeos.dir/build
.PHONY : nodeos/fast

#=============================================================================
# Target rules for targets named closb

# Build rule for target.
closb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 closb
.PHONY : closb

# fast build rule for target.
closb/fast:
	$(MAKE) -f programs/closb/CMakeFiles/closb.dir/build.make programs/closb/CMakeFiles/closb.dir/build
.PHONY : closb/fast

#=============================================================================
# Target rules for targets named keosd

# Build rule for target.
keosd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 keosd
.PHONY : keosd

# fast build rule for target.
keosd/fast:
	$(MAKE) -f programs/keosd/CMakeFiles/keosd.dir/build.make programs/keosd/CMakeFiles/keosd.dir/build
.PHONY : keosd/fast

#=============================================================================
# Target rules for targets named eosio-launcher

# Build rule for target.
eosio-launcher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eosio-launcher
.PHONY : eosio-launcher

# fast build rule for target.
eosio-launcher/fast:
	$(MAKE) -f programs/eosio-launcher/CMakeFiles/eosio-launcher.dir/build.make programs/eosio-launcher/CMakeFiles/eosio-launcher.dir/build
.PHONY : eosio-launcher/fast

#=============================================================================
# Target rules for targets named eosio-blocklog

# Build rule for target.
eosio-blocklog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eosio-blocklog
.PHONY : eosio-blocklog

# fast build rule for target.
eosio-blocklog/fast:
	$(MAKE) -f programs/eosio-blocklog/CMakeFiles/eosio-blocklog.dir/build.make programs/eosio-blocklog/CMakeFiles/eosio-blocklog.dir/build
.PHONY : eosio-blocklog/fast

#=============================================================================
# Target rules for targets named unit_test

# Build rule for target.
unit_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_test
.PHONY : unit_test

# fast build rule for target.
unit_test/fast:
	$(MAKE) -f unittests/CMakeFiles/unit_test.dir/build.make unittests/CMakeFiles/unit_test.dir/build
.PHONY : unit_test/fast

#=============================================================================
# Target rules for targets named plugin_test

# Build rule for target.
plugin_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plugin_test
.PHONY : plugin_test

# fast build rule for target.
plugin_test/fast:
	$(MAKE) -f tests/CMakeFiles/plugin_test.dir/build.make tests/CMakeFiles/plugin_test.dir/build
.PHONY : plugin_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... base-install"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousConfigure"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalMemCheck"
	@echo "... install/strip"
	@echo "... ExperimentalTest"
	@echo "... NightlyUpdate"
	@echo "... install/local"
	@echo "... NightlyStart"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousBuild"
	@echo "... Continuous"
	@echo "... Experimental"
	@echo "... ExperimentalConfigure"
	@echo "... edit_cache"
	@echo "... NightlyTest"
	@echo "... NightlyCoverage"
	@echo "... install"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyMemCheck"
	@echo "... ContinuousStart"
	@echo "... NightlySubmit"
	@echo "... ContinuousCoverage"
	@echo "... Nightly"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalStart"
	@echo "... list_install_components"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalBuild"
	@echo "... fc"
	@echo "... secp256k1"
	@echo "... test_cypher_suites"
	@echo "... builtins"
	@echo "... softfloat"
	@echo "... chainbase"
	@echo "... chainbase_test"
	@echo "... Inline"
	@echo "... IR"
	@echo "... Logging"
	@echo "... Platform"
	@echo "... Runtime"
	@echo "... WASM"
	@echo "... WAST"
	@echo "... appbase_version"
	@echo "... appbase"
	@echo "... appbase_example"
	@echo "... eosio_chain"
	@echo "... eosio_testing"
	@echo "... run-tests"
	@echo "... everything"
	@echo "... wabt"
	@echo "... dist"
	@echo "... cppcheck"
	@echo "... yubihsm_usb"
	@echo "... yubihsm"
	@echo "... yubihsm_static"
	@echo "... yubihsm_http"
	@echo "... test_pbkdf2"
	@echo "... test_parsing"
	@echo "... test_usb_url"
	@echo "... test_util"
	@echo "... net_plugin"
	@echo "... net_api_plugin"
	@echo "... http_plugin"
	@echo "... http_client_plugin"
	@echo "... chain_plugin"
	@echo "... chain_api_plugin"
	@echo "... producer_plugin"
	@echo "... producer_api_plugin"
	@echo "... history_plugin"
	@echo "... history_api_plugin"
	@echo "... state_history_plugin"
	@echo "... wallet_plugin"
	@echo "... wallet_api_plugin"
	@echo "... txn_test_gen_plugin"
	@echo "... db_size_api_plugin"
	@echo "... login_plugin"
	@echo "... test_control_plugin"
	@echo "... test_control_api_plugin"
	@echo "... nodeos"
	@echo "... closb"
	@echo "... keosd"
	@echo "... eosio-launcher"
	@echo "... eosio-blocklog"
	@echo "... unit_test"
	@echo "... plugin_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

