# CMake generated Testfile for 
# Source directory: /home/kim5/OASISBloc_github/OASISBlocChain/tests
# Build directory: /home/kim5/OASISBloc_github/OASISBlocChain/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(plugin_test "/home/kim5/OASISBloc_github/OASISBlocChain/tests/plugin_test" "--report_level=detailed" "--color_output")
set_tests_properties(plugin_test PROPERTIES  _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;53;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(nodeos_sanity_test "tests/nodeos_run_test.py" "-v" "--sanity-test" "--clean-run" "--dump-error-detail")
set_tests_properties(nodeos_sanity_test PROPERTIES  LABELS "nonparallelizable_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;55;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(nodeos_run_test "tests/nodeos_run_test.py" "-v" "--clean-run" "--dump-error-detail")
set_tests_properties(nodeos_run_test PROPERTIES  LABELS "nonparallelizable_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;57;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(p2p_dawn515_test "tests/p2p_tests/dawn_515/test.sh")
set_tests_properties(p2p_dawn515_test PROPERTIES  LABELS "nonparallelizable_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;60;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(producer-preactivate-feature-test "tests/prod_preactivation_test.py" "--clean-run" "--dump-error-detail")
set_tests_properties(producer-preactivate-feature-test PROPERTIES  LABELS "nonparallelizable_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;67;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(nodeos_protocol_feature_test "tests/nodeos_protocol_feature_test.py" "-v" "--clean-run" "--dump-error-detail")
set_tests_properties(nodeos_protocol_feature_test PROPERTIES  LABELS "nonparallelizable_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;69;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(distributed-transactions-test "tests/distributed-transactions-test.py" "-d" "2" "-p" "4" "-n" "6" "-v" "--clean-run" "--dump-error-detail")
set_tests_properties(distributed-transactions-test PROPERTIES  LABELS "nonparallelizable_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;72;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(restart-scenarios-test-resync "tests/restart-scenarios-test.py" "-c" "resync" "-p4" "-v" "--clean-run" "--dump-error-details")
set_tests_properties(restart-scenarios-test-resync PROPERTIES  LABELS "nonparallelizable_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;74;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(restart-scenarios-test-hard_replay "tests/restart-scenarios-test.py" "-c" "hardReplay" "-p4" "-v" "--clean-run" "--dump-error-details")
set_tests_properties(restart-scenarios-test-hard_replay PROPERTIES  LABELS "nonparallelizable_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;76;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(restart-scenarios-test-none "tests/restart-scenarios-test.py" "-c" "none" "--kill-sig" "term" "-p4" "-v" "--clean-run" "--dump-error-details")
set_tests_properties(restart-scenarios-test-none PROPERTIES  LABELS "nonparallelizable_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;78;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(validate_dirty_db_test "tests/validate-dirty-db.py" "-v" "--clean-run" "--dump-error-detail")
set_tests_properties(validate_dirty_db_test PROPERTIES  LABELS "nonparallelizable_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;81;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(launcher_test "tests/launcher_test.py" "-v" "--clean-run" "--dump-error-detail")
set_tests_properties(launcher_test PROPERTIES  LABELS "nonparallelizable_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;83;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(db_modes_test "tests/db_modes_test.sh")
set_tests_properties(db_modes_test PROPERTIES  WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;85;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(version-label-test "tests/version-label.sh")
set_tests_properties(version-label-test PROPERTIES  WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;86;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(nodeos_sanity_lr_test "tests/nodeos_run_test.py" "-v" "--sanity-test" "--clean-run" "--dump-error-detail")
set_tests_properties(nodeos_sanity_lr_test PROPERTIES  LABELS "long_running_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;89;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(nodeos_run_check_lr_test "tests/nodeos_run_test.py" "-v" "--clean-run" "--dump-error-detail")
set_tests_properties(nodeos_run_check_lr_test PROPERTIES  LABELS "long_running_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;91;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(nodeos_remote_lr_test "tests/nodeos_run_remote_test.py" "-v" "--clean-run" "--dump-error-detail")
set_tests_properties(nodeos_remote_lr_test PROPERTIES  LABELS "long_running_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;93;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(nodeos_forked_chain_lr_test "tests/nodeos_forked_chain_test.py" "-v" "--wallet-port" "9901" "--clean-run" "--dump-error-detail")
set_tests_properties(nodeos_forked_chain_lr_test PROPERTIES  LABELS "long_running_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;99;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(nodeos_voting_lr_test "tests/nodeos_voting_test.py" "-v" "--wallet-port" "9902" "--clean-run" "--dump-error-detail")
set_tests_properties(nodeos_voting_lr_test PROPERTIES  LABELS "long_running_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;102;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(nodeos_under_min_avail_ram_lr_test "tests/nodeos_under_min_avail_ram.py" "-v" "--wallet-port" "9904" "--clean-run" "--dump-error-detail")
set_tests_properties(nodeos_under_min_avail_ram_lr_test PROPERTIES  LABELS "long_running_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;105;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(nodeos_irreversible_mode_lr_test "tests/nodeos_irreversible_mode_test.py" "-v" "--clean-run" "--dump-error-detail")
set_tests_properties(nodeos_irreversible_mode_lr_test PROPERTIES  LABELS "long_running_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;108;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(nodeos_startup_catchup_lr_test "tests/nodeos_startup_catchup.py" "-v" "--clean-run" "--dump-error-detail")
set_tests_properties(nodeos_startup_catchup_lr_test PROPERTIES  LABELS "long_running_tests" TIMEOUT "3000" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;111;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
add_test(nodeos_multiple_version_protocol_feature_mv_test "tests/nodeos_multiple_version_protocol_feature_test.py" "-v" "--clean-run" "--dump-error-detail" "--alternate-version-labels-file" "/home/kim5/OASISBloc_github/OASISBlocChain/tests/multiversion_paths.conf")
set_tests_properties(nodeos_multiple_version_protocol_feature_mv_test PROPERTIES  LABELS "mixed_version_tests" WORKING_DIRECTORY "/home/kim5/OASISBloc_github/OASISBlocChain" _BACKTRACE_TRIPLES "/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;117;add_test;/home/kim5/OASISBloc_github/OASISBlocChain/tests/CMakeLists.txt;0;")
